server.port=8080

app.name=Employee Management System - Spring Data JPA
app.version=4.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

management.endpoints.web.exposure.include=health,info,metrics

spring.main.banner-mode=off
logging.level.org.hibernate.SQL=DEBUG